### ISSUE TITLE
ViewBackward0 is a view and its base or another view of its base has been modified inplace. 

### ISSUE THREAD

**Issue by RBZ-99** [duxiaodan/intrinsic-lora#1]
In the 2nd iteration, the line: `model_pred = unet(original_image_embeds, timesteps, encoder_hidden_states).sample` leads to this error:  RuntimeError: Output 0 of ViewBackward0 is a view and its base or another view of its base has been modified inplace. This view is the output of a function that returns multiple views. Such functions do not allow the output views to be modified inplace. You should replace the inplace operation by an out-of-place one.

**Comment by duxiaodan** [comment]
Hello! Which file are you using? Could you please also post the entire error message here? Thank you.

**Comment by RBZ-99** [comment]
I am using "sd_single_diode_pseudo_normal.py" and I get this error trace:

Traceback (most recent call last):
  File "sd_single_diode_pseudo_normal.py", line 1146, in <module>
    main()
  File "sd_single_diode_pseudo_normal.py", line 1034, in main
    model_pred = unet(original_image_embeds, timesteps, encoder_hidden_states).sample
  File "/home/user1/anaconda3/envs/env0/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user1/anaconda3/envs/env0/lib/python3.8/site-packages/diffusers/models/unet_2d_condition.py", line 1075, in forward
    sample, res_samples = downsample_block(
  File "/home/user1/anaconda3/envs/env0/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user1/anaconda3/envs/env0/lib/python3.8/site-packages/diffusers/models/unet_2d_blocks.py", line 1160, in forward
    hidden_states = attn(
  File "/home/user1/anaconda3/envs/env0/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user1/anaconda3/envs/env0/lib/python3.8/site-packages/diffusers/models/transformer_2d.py", line 392, in forward
    hidden_states = block(
  File "/home/user1/anaconda3/envs/env0/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user1/anaconda3/envs/env0/lib/python3.8/site-packages/diffusers/models/attention.py", line 288, in forward
    attn_output = self.attn1(
  File "/home/user1/anaconda3/envs/env0/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user1/anaconda3/envs/env0/lib/python3.8/site-packages/diffusers/models/attention_processor.py", line 522, in forward
    return self.processor(
  File "/home/user1/anaconda3/envs/env0/lib/python3.8/site-packages/diffusers/models/attention_processor.py", line 729, in __call__
    query = attn.to_q(hidden_states, *args)
  File "/home/user1/anaconda3/envs/env0/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user1/anaconda3/envs/env0/lib/python3.8/site-packages/diffusers/models/lora.py", line 433, in forward
    out = super().forward(hidden_states) + (scale * self.lora_layer(hidden_states))
  File "/home/user1/anaconda3/envs/env0/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user1/anaconda3/envs/env0/lib/python3.8/site-packages/diffusers/models/lora.py", line 220, in forward
    down_hidden_states = self.down(hidden_states.to(dtype))
  File "/home/user1/anaconda3/envs/env0/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user1/anaconda3/envs/env0/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: Output 0 of ViewBackward0 is a view and its base or another view of its base has been modified inplace. This view is the output of a function that returns multiple views. Such functions do not allow the output views to be modified inplace. You should replace the inplace operation by an out-of-place one.

**Comment by duxiaodan** [comment]
The original code paired with my original training script seems to work well on my machine. Have you made any changes to the code? Could you try once more with the untouched python code and let me know if you still have the same problem?

**Comment by duxiaodan** [comment]
Close for now. Feel free to reopen it if needed
